
desc 'UCLib 针对私有库快速升级维护 eg: fastlane UCLib target:MGDataBinder tag:1.0.0.3 msg:新增模型数组方法'
lane :UCLib do |options|

# 打标签需要和podspec的版本对应
tagName = options[:tag]
# 被上传的目标podspec文件
targetName = options[:target]
# 本次更新的内容
msgName = options[:msg]

# pod install （使Example与pod下来的库产生关联）
cocoapods(
clean: true,
podfile: "./Example/Podfile"
)

pod_lib_lint(
	# sources: ['http://gitlab.umooc.com.cn/malgee/umspecs.git','https://cdn.cocoapods.org/'],
	allow_warnings: true, 
	verbose: true,
	no_clean: true,
	use_libraries: true
	)

git_add(path: ".")
git_commit(path: ".", message: "#{msgName}")

push_to_git_remote


if git_tag_exists(tag: tagName)
    UI.message("发现tag:#{tagName} 之前有tag,删除原来的标签🚀")
    remove_tag(tag:tagName)
end

# 打标签
add_git_tag(tag: tagName)
push_git_tags

pod_push(
	path: "#{targetName}.podspec", 
	repo: "UCSpecs", 
	verbose: true,
	allow_warnings: true,
	use_libraries: true,
	# sources: ['http://gitlab.umooc.com.cn/malgee/umspecs.git','https://cdn.cocoapods.org/'],
	# use_libraries:true
	)

end
