# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

####################################################

# eg:  fastlane MGLibs lib:MGDataBinder tag:1.0.0 message:使用fastlane更新

####################################################

import_from_git(
	url: 'https://github.com/Maling1255/MGActionLanes.git', 
	branch: 'main', 
	path: 'fastlane/ios_fastfile.rb'
	)

default_platform(:ios)

platform :ios do
  desc "升级MGDataBinder库"
  lane :MGLibs do |options|
  	libName = options[:lib]
    message = options[:message]
    tag = options[:tag]
    is_public = options[:public]
  	mg_update_lib(libName:libName, tag:tag, message:message, is_public:is_public)

  end
end
